name: Pull Request

on:
  pull_request:
    branches: [ main]
    types: [opened, reopened, ready_for_review]
  push:
    branches:
      - '*'

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt-get update && \
          apt-get install -y \
          libgeos-dev
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest

  format_code:

    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Set the Python version you want to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Format code with black
      run: |
        black .
    - name: Add env variable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}